GET http://localhost:3000/api/bail
###
POST  http://localhost:3000/api/bail
Content-Type: application/json

{
    "bailDate":"2022-07-15",
    "bailerName": "Mercy",
    "bailerPhoneNumber": "08033025796",
    "bailerAdress": "Hazel Lane Pearl Garden Estate",
    "bailerEmail": "Mercy@gmail.com",
    "bailBond": "Fine shouldn't be paid"
}

###

GET  http://localhost:3000/api/bail/62f1114647979679c124a438

###

PATCH   http://localhost:3000/api/bail/62f6441ce24874116da7ea60
Content-Type: application/json

{

    "crimeOffendersId":"1",
    "bailDate":"2022-07-15",
    "bailerName": "James",
    "bailerPhoneNumber": "08033022880",
    "bailerAdress": "Aster Lane Pearl Garden Estate",
    "bailerEmail": "James@gmail.com"

}
###
DELETE http://localhost:3000/api/bail/62f6441ce24874116da7ea60
