GET http://localhost:3000/api/correctioncenters
###
POST  http://localhost:3000/api/correctioncenters
Content-Type: application/json

{"name":"danny"}

###

GET  http://localhost:3000/api/correctioncenters/62f0e54eccc817e0747789dd

###

PATCH   http://localhost:3000/api/correctioncenters/62f0fd79db392ea0356d21f5
Content-Type: application/json

{"name":"may"}
###
DELETE http://localhost:3000/api/correctioncenters/62f0fd79db392ea0356d21f5
